name: nomokit
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  flutter_bluetooth_serial: ^0.4.0
  permission_handler: ^10.2.0
  usb_serial: ^0.4.0
  url_launcher: ^6.1.11
  flutter_spinkit: ^5.2.0
  flutter_inappwebview: ^6.0.0-beta.23
  http: ^0.13.6
  path_provider: ^2.0.15
  share_plus: ^7.0.1

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/img/
    - assets/gui/
    - assets/gui/chunks/
    - assets/gui/static/assets/
    - assets/gui/static/blocks-media/
    - assets/gui/static/blocks-media/extensions/
    - assets/gui/static/blocks-media/icons/
    - assets/gui/static/extensions/
  uses-material-design: true
